name: irop
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - aom=3.5.0
  - async-timeout=4.0.2
  - attrs=23.1.0
  - blosc=1.21.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - certifi=2023.5.7
  - chardet=5.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - contourpy=1.0.7
  - curl=8.1.2
  - cycler=0.11.0
  - dav1d=1.2.1
  - double-conversion=3.2.0
  - eigen=3.4.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.4
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - gettext=0.21.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.76.3
  - glib-tools=2.76.3
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - harfbuzz=7.3.0
  - hdf4=4.2.15
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.4
  - imageio=2.28.1
  - jsoncpp=1.9.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.1.2
  - libcxx=16.0.5
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.52.0
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libspatialindex=1.9.3
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.13.0
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.11.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=16.0.5
  - llvmlite=0.40.0
  - loguru=0.7.0
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4
  - nettle=3.8.1
  - nlohmann_json=3.11.2
  - nspr=4.35
  - nss=3.89
  - numba=0.57.0
  - numpy=1.24.3
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.1
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=2.0.2
  - patsy=0.5.3
  - pcre2=10.40
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.5.1
  - pooch=1.7.0
  - proj=9.2.0
  - pthread-stubs=0.4
  - pugixml=1.11.4
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - pyvista=0.38.1
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.31.0
  - rtree=1.0.1
  - scipy=1.10.1
  - scooby=0.7.2
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=67.7.2
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.42.0
  - statsmodels=0.14.0
  - svt-av1=1.4.1
  - tabulate=0.9.0
  - tbb=2021.9.0
  - tbb-devel=2021.9.0
  - tk=8.6.12
  - tornado=6.3.2
  - tqdm=4.65.0
  - trimesh=3.22.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=2.0.2
  - utfcpp=3.2.3
  - vtk=9.2.6
  - vtk-base=9.2.6
  - vtk-io-ffmpeg=9.2.6
  - wheel=0.40.0
  - wslink=1.10.2
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yarl=1.9.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - cli-exit-tools==1.2.3.2
      - dataclass-csv==1.4.0
      - dill==0.3.6
      - lib-detect-testenv==2.0.3
      - multiprocess==0.70.14
      - tetgen==0.6.3
      - wrapt==1.15.0
      - wrapt-timeout-decorator==1.3.12.2