[build-system]
requires = [
    "setuptools>=60",
    "wheel",
    "taichi",
    "meshtaichi_patcher",
    "pyvista",
    "tqdm",
    "line_profiler",
    "matplotlib",
    "plotly",
    "trimesh",
]

[tool.black]
line-length = 140
target-version = ['py39']
skip-string-normalization = true
