[pytest]
# If a pytest section is found in one of the possible config files
# (pytest.ini, tox.ini or setup.cfg), then pytest will not look for any others,
# so if you add a pytest config section elsewhere,
# you will need to delete this section from setup.cfg.
norecursedirs =
    migrations

python_files =
    test_*.py
    *_test.py
    tests.py
addopts =
    -ra
    --strict-markers
    --doctest-modules
    --doctest-glob=\*.rst
    --tb=short
    --pyargs
# The order of these options matters. testpaths comes after addopts so that
# irregular_object_packing in testpaths is interpreted as
# --pyargs irregular_object_packing.
# Any tests in the src/ directory (that is, tests installed with the package)
# can be run by any user with pytest --pyargs irregular_object_packing.
# Packages that are sensitive to the host machine, most famously NumPy,
# include tests with the installed package so that any user can check
# at any time that everything is working properly.
# If you do choose to make installable tests, this will run the installed
# tests as they are actually installed (same principle as when we ensure that
# we always test the installed version of the package).
# If you have no need for this (and your src/ directory is very large),
# you can save a few milliseconds on testing by telling pytest not to search
# the src/ directory by removing
# --pyargs and irregular_object_packing from the options here.
testpaths =
    irregular_object_packing
    tests/

# Idea from: https://til.simonwillison.net/pytest/treat-warnings-as-errors
filterwarnings =
    error
# You can add exclusions, some examples:
#    ignore:'irregular_object_packing' defines default_app_config:PendingDeprecationWarning::
#    ignore:The {{% if:::
#    ignore:Coverage disabled via --no-cov switch!
